/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    ChatView: typeof import('./src/components/ChatView.vue')['default']
    ContactView: typeof import('./src/components/shop-view/views/ContactView.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HomePage: typeof import('./src/components/HomePage.vue')['default']
    HomeView: typeof import('./src/components/shop-view/views/HomeView.vue')['default']
    ItemPriceSection: typeof import('./src/components/shop-view/sections/ItemPriceSection.vue')['default']
    LoginPage: typeof import('./src/components/LoginPage.vue')['default']
    LogoSection: typeof import('./src/components/shop-view/sections/LogoSection.vue')['default']
    LookBookView: typeof import('./src/components/shop-view/views/LookBookView.vue')['default']
    NavigationDrawer: typeof import('./src/components/NavigationDrawer.vue')['default']
    NavigationSection: typeof import('./src/components/shop-view/sections/NavigationSection.vue')['default']
    NewsView: typeof import('./src/components/shop-view/views/NewsView.vue')['default']
    PagesTopBar: typeof import('./src/components/PagesTopBar.vue')['default']
    RegistrationPage: typeof import('./src/components/RegistrationPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SeasonsSection: typeof import('./src/components/shop-view/sections/SeasonsSection.vue')['default']
    SeasonView: typeof import('./src/components/shop-view/views/SeasonView.vue')['default']
    SettingsPage: typeof import('./src/components/SettingsPage.vue')['default']
    ShopItemView: typeof import('./src/components/shop-view/views/ShopItemView.vue')['default']
    ShopView: typeof import('./src/components/shop-view/views/ShopView.vue')['default']
    TermsView: typeof import('./src/components/shop-view/views/TermsView.vue')['default']
    TopBar: typeof import('./src/components/TopBar.vue')['default']
    UserPage: typeof import('./src/components/UserPage.vue')['default']
    WelcomeDialog: typeof import('./src/components/WelcomeDialog.vue')['default']
  }
}
