version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://root:example@mongodb:27017/devTemp  # Add credentials here
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    environment:
      - BACKEND_URL=http://dev-temp-backend:4000  # Set backend URL for frontend if needed

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

volumes:
  mongodb_data:
    driver: local
